[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[window]
decorations = "none"

[general]
# themes from https://github.com/alacritty/alacritty-theme
#import = [" ~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
import = [" ~/.config/alacritty/themes/themes/catppuccin.toml"]

[terminal]
[terminal.shell]
program = "tmux"
