- name: Install graphify
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tags: ai-coding
  become_user: "{{ current_user }}"
  tasks:
    - name: Install Claude code
      tags: ai-coding
      shell: |
        uv tool install graphifyy

- name: Install AI Coding CLIs
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tags: ai-coding-cli
  become_user: "{{ current_user }}"
  tasks:
    - name: Install Claude code
      tags: ai-coding-cli
      shell: |
        curl -fsSL https://claude.ai/install.sh | bash
        graphify install
    - name: Install Codex
      tags: ai-coding-cli
      shell: |
        npm i -g @openai/codex
        graphify install --platform codex
    - name: Install OpenCode
      tags: ai-coding-cli
      shell: |
        curl -fsSL https://opencode.ai/install | bash
        graphify install --platform opencode
