- name: Install Nginx Server 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Install Nginx Server
      dnf:
        name: nginx
        state: present

- name: Install MySQL 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Install MySQL
      dnf:
        name: mariadb  
        state: present
    - name: Starting and Enabling
      systemd:
        name: mariadb
        state: started


- name: Install Docker 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Removing Old Docker
      ignore_errors: true
      shell: |
        dnf remove docker \
        docker-client \
        docker-client-latest \
        docker-common \
        docker-latest \
        docker-latest-logrotate \
        docker-logrotate \
        docker-selinux \
        docker-engine-selinux \
        docker-engine -y
    - name: Adding Docker Repo
      shell: |
        dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    - name: Installing Docker 
      shell: |
        dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
    - name: Starting and Enabling Docker
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Install helm 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Removing Old Helm
      ignore_errors: true
      shell: |
        rm -rf /usr/local/bin/helm
    - name: Installing Latest Helm
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod +x get_helm.sh
        ./get_helm.sh
        rm -rf get_helm.sh
