- name: Install Nginx Server 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Install Nginx Server
      dnf:
        name: nginx
        state: present

- name: Install MySQL 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Install MySQL
      dnf:
        name: mariadb  
        state: present
    - name: Starting and Enabling
      systemd:
        name: mariadb
        state: started


- name: Install Docker 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  vars:
    user_to_configure: "{{ current_user }}"
  tasks:
    - name: Removing Old Docker
      ignore_errors: true
      shell: |
        dnf remove docker \
        docker-client \
        docker-client-latest \
        docker-common \
        docker-latest \
        docker-latest-logrotate \
        docker-logrotate \
        docker-selinux \
        docker-engine-selinux \
        docker-engine -y
    - name: Adding Docker Repo
      shell: |
        dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    - name: Installing Docker 
      shell: |
        dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
        sudo usermod -aG docker {{ user_to_configure }}  
    - name: Starting and Enabling Docker
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Install helm 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Removing Old Helm
      ignore_errors: true
      shell: |
        rm -rf /usr/local/bin/helm
    - name: Installing Latest Helm
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod +x get_helm.sh
        ./get_helm.sh
        rm -rf get_helm.sh

- name: Install Terraform 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Adding Terraform repo
      shell: |
        dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    - name: Installing AzureCLI
      shell: |
        dnf -y install terraform

- name: Install AzureCLI 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Adding AzureCLI repo
      shell: |
        rpm --import https://packages.microsoft.com/keys/microsoft.asc
        echo -e "[azure-cli]
        name=Azure CLI
        baseurl=https://packages.microsoft.com/yumrepos/azure-cli
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/azure-cli.repo
    - name: Installing AzureCLI
      shell: |
        dnf install azure-cli -y

- name: Install postman 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Removing Old Postman
      ignore_errors: true
      shell: |
        rm -rf /usr/bin/postman
        rm -rf /opt/Postman/Postman
    - name: Installing Postman
      shell: |
        wget https://dl.pstmn.io/download/latest/linux64 -O postman-linux-x64.tar.gz
        tar xvzf postman-linux-x64.tar.gz -C /opt
        ln -s /opt/Postman/Postman /usr/bin/postman

        cat << EOF > ~/.local/share/applications/postman2.desktop
        [Desktop Entry]
        Name=Postman
        GenericName=API Client
        X-GNOME-FullName=Postman API Client
        Comment=Make and view REST API calls and responses
        Keywords=api;
        Exec=/opt/Postman/Postman
        Terminal=false
        Type=Application
        Icon=/opt/Postman/app/resources/app/assets/icon.png
        Categories=Development;Utilities;
        EOF
