- name: Installing Regular tools
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  become_user: "{{ current_user }}"
  tasks:
    - name: Install Curl
      apt:
        name: curl
        state: present
    - name: Install Rust
      shell: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Setup Rust
      shell: |
        rustup override set stable
        rustup update stable
    - name: Install Git 
      apt:
        name: git
        state: present
    - name: Install unzip 
      apt:
        name: unzip
        state: present
    - name: Install Tree
      apt:
        name: tree
        state: present
    - name: Install Snapd
      apt:
        name: snapd
        state: present
    - name: Install light
      apt:
        name: light
        state: present
    - name: Install maim 
      apt:
        name: maim
        state: present
    - name: Install xclip
      apt:
        name: xclip
        state: present
    - name: Install pavucontrol
      apt:
        name: pavucontrol
        state: present
    - name: Install volumeicon
      apt:
        name: volumeicon
        state: present
    - name: Install fzf
      apt:
        name: fzf
        state: present
    - name: Install picom
      apt:
        name: picom
        state: present
    - name: Install Blueman
      apt:
        name: blueman
        state: present
    - name: Install RipGrep
      apt:
        name: ripgrep
        state: present

- name: Install Alacritty
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  become_user: "{{ current_user }}"
  tasks:
    - name: Install required packages
      apt:
        name:
          - cmake
          - g++
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
          - python3
        state: present
        update_cache: yes
    - name: Download Alacritty Repo
      shell: |
        git clone https://github.com/alacritty/alacritty.git ~/alacritty
    - name: Installing Alacritty using cargo
      shell: |
        cd alacritty
        cargo build --release
    - name: Setup Themes
      shell: |
        mkdir -p ~/.config/alacritty/themes
        git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

- name: Install tmux 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Installing tmux 
      apt:
        name: tmux
        state: present

- name: Install neovim 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Installing neovim 
      apt:
        name: neovim
        state: present

- name: Install i3 Window Manager 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Installing i3 
      apt:
        name: i3
        state: present

# - name: Install Brave Browser
#   hosts: localhost
#   become: true  # Run tasks with elevated privileges (sudo)
#   tasks:
#     - name: Add Brave Repo
#       shell: |
#         dnf-3 config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
#         rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
#     - name: Install brave 
#       dnf:
#         name: brave-browser 
#         state: present
