- name: Installing Regular tools
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Install required packages
      apt:
        name:
          - bash-completion
          - unzip
          - tree
          - snapd
          - light
          - pavucontrol
          - maim
          - xclip
          - fzf
          - picom
          - blueman
          - ripgrep
          - cmake
          - g++
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
          - python3
        state: present

- name: Installing Rust
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  become_user: "{{ current_user }}"
  tasks:
    - name: Install Rust
      shell: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Setup Rust
      ignore_errors: true
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"  # Make sure rustup is in PATH
        rustup override set stable
        rustup update stable

- name: Install Alacritty
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  become_user: "{{ current_user }}"
  tasks:
    - name: Download Alacritty Repo
      shell: |
        git clone https://github.com/alacritty/alacritty.git ~/alacritty
    - name: Installing Alacritty using cargo
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"  # Make sure cargo is in the PATH
        cd ~/alacritty
        cargo build --release
    - name: Setup Themes
      shell: |
        mkdir -p ~/.config/alacritty/themes
        git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

- name: Install tmux 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Installing tmux 
      apt:
        name: tmux
        state: present

- name: Install neovim 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Installing neovim 
      apt:
        name: neovim
        state: present

- name: Install i3 Window Manager 
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)
  tasks:
    - name: Installing i3 
      apt:
        name: i3
        state: present

# - name: Install Brave Browser
#   hosts: localhost
#   become: true  # Run tasks with elevated privileges (sudo)
#   tasks:
#     - name: Add Brave Repo
#       shell: |
#         dnf-3 config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
#         rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
#     - name: Install brave 
#       dnf:
#         name: brave-browser 
#         state: present
