-- local ok, claudecode = pcall(require, "claudecode")
-- if ok then
--   claudecode.setup({
--     terminal_cmd = "claude",
--   })
-- end
-- 
-- local function get_claude_win_name()
--   local cwd_basename = vim.fn.fnamemodify(vim.fn.getcwd(), ":t")
--   return cwd_basename .. "-claude"
-- end
-- 
-- local function tmux_toggle_claude()
--   if vim.trim(vim.fn.system("printenv TMUX")) == "" then
--     vim.notify("Not inside a tmux session", vim.log.levels.WARN)
--     return
--   end
-- 
--   local win_name = get_claude_win_name()
--   local escaped_name = vim.fn.shellescape(win_name)
--   local win_exists = tonumber(vim.fn.system(
--     "tmux list-windows -F '#{window_name}' | grep -Fx -c " .. escaped_name
--   )) or 0
-- 
--   if win_exists > 0 then
--     vim.fn.system("tmux select-window -t " .. escaped_name)
--   else
--     vim.fn.system("tmux new-window -n " .. escaped_name .. " " .. vim.fn.shellescape("claude"))
--   end
-- end
-- 
-- local function tmux_send_to_claude(text)
--   if vim.trim(vim.fn.system("printenv TMUX")) == "" then
--     vim.cmd("ClaudeCodeSend")
--     return
--   end
-- 
--   local win_name = get_claude_win_name()
--   local escaped_name = vim.fn.shellescape(win_name)
--   local win_exists = tonumber(vim.fn.system(
--     "tmux list-windows -F '#{window_name}' | grep -Fx -c " .. escaped_name
--   )) or 0
-- 
--   if win_exists == 0 then
--     tmux_toggle_claude()
--   end
-- 
--   local panes_output = vim.fn.system("tmux list-panes -t " .. escaped_name .. " -F '#{pane_id}'")
--   local target = nil
--   for line in panes_output:gmatch("[^\r\n]+") do
--     if line ~= "" then
--       target = line
--       break
--     end
--   end
-- 
--   if target == nil then
--     vim.notify("Could not find Claude tmux pane", vim.log.levels.ERROR)
--     return
--   end
-- 
--   vim.fn.system("tmux load-buffer -", text)
--   vim.fn.system("tmux paste-buffer -t " .. target)
--   vim.fn.system("tmux send-keys -t " .. target .. " Enter")
-- end
-- 
-- local function get_visual_selection_text()
--   local mode = vim.fn.mode()
--   local start_pos
--   local end_pos
-- 
--   if mode == "v" or mode == "V" or mode == "\22" then
--     start_pos = vim.fn.getpos("v")
--     end_pos = vim.fn.getcurpos()
--   else
--     start_pos = vim.fn.getpos("'<")
--     end_pos = vim.fn.getpos("'>")
--     mode = vim.fn.visualmode()
--   end
-- 
--   local srow, scol = start_pos[2], start_pos[3]
--   local erow, ecol = end_pos[2], end_pos[3]
-- 
--   if srow == 0 or erow == 0 then
--     return ""
--   end
-- 
--   if srow > erow or (srow == erow and scol > ecol) then
--     srow, erow = erow, srow
--     scol, ecol = ecol, scol
--   end
-- 
--   if mode == "V" then
--     return table.concat(vim.api.nvim_buf_get_lines(0, srow - 1, erow, false), "\n")
--   end
-- 
--   if mode == "\22" then
--     vim.notify("Blockwise visual send is not supported yet", vim.log.levels.WARN)
--     return ""
--   end
-- 
--   if ecol >= 2147483647 then
--     local end_line = vim.api.nvim_buf_get_lines(0, erow - 1, erow, false)[1] or ""
--     ecol = #end_line + 1
--   end
-- 
--   local lines = vim.api.nvim_buf_get_text(0, srow - 1, math.max(scol - 1, 0), erow - 1, math.max(ecol, 0), {})
--   return table.concat(lines, "\n")
-- end
-- 
-- local function send_visual_to_claude()
--   local text = get_visual_selection_text()
--   if text == "" then
--     vim.notify("No visual selection to send", vim.log.levels.WARN)
--     return
--   end
-- 
--   tmux_send_to_claude(text)
-- end
-- 
-- local wk_ok, wk = pcall(require, "which-key")
-- if wk_ok then
--   wk.add({ { "<leader>a", group = "AI/Claude Code" } })
-- end
-- 
-- -- vim.keymap.set("n", "<leader>ac", "<cmd>ClaudeCode<cr>", { desc = "Toggle Claude" })
-- vim.keymap.set("n", "<leader>af", "<cmd>ClaudeCodeFocus<cr>", { desc = "Focus Claude" })
-- vim.keymap.set("n", "<leader>ar", "<cmd>ClaudeCode --resume<cr>", { desc = "Resume Claude" })
-- vim.keymap.set("n", "<leader>aC", "<cmd>ClaudeCode --continue<cr>", { desc = "Continue Claude" })
-- vim.keymap.set("n", "<leader>am", "<cmd>ClaudeCodeSelectModel<cr>", { desc = "Select Claude model" })
-- vim.keymap.set("n", "<leader>ab", "<cmd>ClaudeCodeAdd %<cr>", { desc = "Add current buffer" })
-- vim.keymap.set("x", "<leader>as", send_visual_to_claude, { desc = "Send to Claude", silent = true })
-- vim.keymap.set("n", "<leader>aa", "<cmd>ClaudeCodeDiffAccept<cr>", { desc = "Accept diff" })
-- vim.keymap.set("n", "<leader>ad", "<cmd>ClaudeCodeDiffDeny<cr>", { desc = "Deny diff" })
-- vim.keymap.set({ "n", "t" }, "<leader>at", tmux_toggle_claude, { desc = "Toggle Claude (tmux window)" })
-- 
-- local tree_filetypes = { "NvimTree", "neo-tree", "oil", "minifiles", "netrw" }
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = tree_filetypes,
--   callback = function(args)
--     vim.keymap.set("n", "<leader>as", "<cmd>ClaudeCodeTreeAdd<cr>", {
--       buffer = args.buf,
--       desc = "Add file",
--     })
--   end,
-- })
