- name: Install System Application 
  import_playbook: playbooks/system.yaml
  vars:
    current_user: "mahakal"
    
- name: Install Languages 
  import_playbook: playbooks/language.yaml

- name: Install K8S Stuff 
  import_playbook: playbooks/k8s.yaml

- name: Install DevOps Tools 
  import_playbook: playbooks/devops.yaml
